// pages/FinalPage.jsx
import { useEffect, useState } from "react";
import API from "../services/api";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export default function FinalPage() {
  const [cars, setCars] = useState([]);

  useEffect(() => {
    fetchCars();
  }, []);

  const fetchCars = async () => {
    const res = await API.get("/cars");
    setCars(res.data);
  };

  // 🔥 Generate Professional PDF
  const generatePDF = () => {
    const doc = new jsPDF();

    // Title (Centered)
    doc.setFontSize(18);
    doc.text("Car Price Report", 105, 15, { align: "center" });

    // Date
    doc.setFontSize(10);
    doc.text(
      `Date: ${new Date().toLocaleDateString()}`,
      14,
      25
    );

    // Prepare Table Data
    const tableData = cars.map((car, index) => [
      index + 1,
      car.model,
      `${car.price}  INR`,
      `${car.discountPercentage || 0}%`,
      `${car.finalPrice} INR`
    ]);

    // Table
    autoTable(doc, {
      startY: 35,
      head: [
        ["S.No", "Car Model", "Original Price", "Discount %", "Final Price"]
      ],
      body: tableData,

      styles: {
        fontSize: 10,
        cellPadding: 3
      },

      headStyles: {
        fillColor: [37, 99, 235], // Blue
        textColor: 255,
        fontStyle: "bold"
      },

      alternateRowStyles: {
        fillColor: [240, 240, 240]
      },

      columnStyles: {
        4: { textColor: [0, 128, 0], fontStyle: "bold" } // Final price column
      }
    });

    // Footer
    doc.setFontSize(9);
    doc.text(
      "Generated by Admin Panel",
      14,
      doc.internal.pageSize.height - 10
    );

    doc.save("Car_Report.pdf");
  };

  return (
    <div className="p-6">
      
      {/* Header */}
      <div className="flex justify-between items-center mb-6">
        <h2 className="text-2xl font-bold text-gray-700">
          Final Price Report
        </h2>

        <button
          onClick={generatePDF}
          className="bg-blue-500 text-white px-5 py-2 rounded-lg hover:bg-blue-600 transition shadow"
        >
          Download PDF
        </button>
      </div>

      {/* Table UI (Premium Look) */}
      <div className="bg-white rounded-xl shadow-md p-4 overflow-x-auto">
        <table className="w-full text-left border-collapse">
          
          <thead>
            <tr className="bg-blue-500 text-white">
              <th className="p-3">#</th>
              <th className="p-3">Car</th>
              <th className="p-3">Original</th>
              <th className="p-3">Discount</th>
              <th className="p-3">Final</th>
            </tr>
          </thead>

          <tbody>
            {cars.map((car, index) => (
              <tr
                key={car._id}
                className="border-b hover:bg-gray-50 transition"
              >
                <td className="p-3">{index + 1}</td>
                <td className="p-3 font-semibold">{car.model}</td>
                <td className="p-3 text-gray-600">
                  ₹{car.price}
                </td>
                <td className="p-3 text-red-500">
                  {car.discountPercentage || 0}%
                </td>
                <td className="p-3 text-green-600 font-bold">
                  ₹{car.finalPrice}
                </td>
              </tr>
            ))}
          </tbody>

        </table>
      </div>

    </div>
  );
}